name: "Compile Resume"
description: "Consumes the LaTex files to produce main.pdf"

runs:
    using: "composite"
    steps:
        - name: Compile into PDF
          uses: xu-cheng/latex-action@v3
          with:
            working_directory: src
            root_file: main.tex
        - name: Upload PDF File
          uses: actions/upload-artifact@v4
          with:
            name: output
            path: ./src/main.pdf
