name: Compile Resume into PDF

on:
    workflow_dispatch:
    pull_request:
        branches: [ $default-branch ]
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/compile
