name: Compile and Publish

on:
    workflow_dispatch:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/compile
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: output
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                files: main.pdf
                draft: true
        needs: [build]
